In [1]:
a = np.array([1,2,3,4])
a+a

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [4]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [5]:
a**2 


array([ 1,  4,  9, 16])

In [9]:
# ALL ARITHMETIC OPERATOR ELEMENTWISE
b = np.ones(4) +4
b

array([5., 5., 5., 5.])

In [7]:
a-b

array([-4., -3., -2., -1.])

In [8]:
a*b

array([ 5., 10., 15., 20.])

In [10]:
# MATRIX MULPLICATION 
c = np.diag([1,2,3,4])
print(c*c)
print("****************************")


[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
****************************


In [11]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [15]:
a = np.array([1,2,3,4])
b = np.array([1,2,2,3,])
a==b


array([ True,  True, False, False])

In [16]:
a>b

array([False, False,  True,  True])

In [17]:
np.array_equal(a,b)

False

In [18]:
# logical operation ----------


In [19]:
a= np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype = bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [20]:
np.logical_and(a,b)

array([ True, False, False, False])

In [24]:
# mathematical operations ---------
a = np.arange(5)
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [25]:
np.log(a)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_17828\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [26]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [27]:
np.sum(a)

np.int64(10)

In [28]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [29]:
x.sum(axis=0)  #columns wise sum --

array([4, 6])

In [30]:
x.sum(axis=1)

array([3, 7])

In [31]:
x.min()

np.int64(1)

In [32]:
x.max()

np.int64(4)

In [33]:
x.argmin()  # index of min value

np.int64(0)

In [34]:
x.argmax()       #index of max

np.int64(3)

In [35]:
# logical operation 
print("************************************************")

************************************************


In [37]:
np.all([True,True,False])  #and operator like

np.False_

In [38]:
np.any([True,False,False]) #like or operator

np.True_

In [39]:
a = np.zeros((50,50))
np.any(a != 0)

np.False_

In [9]:
a = np.array([1,1,1,1])
b= np.array([1,2,2,2])
c = np.array([6,4,4,4])
((a<=b) & (b<=c)).all()

np.True_

In [5]:
#broadcasting 

a = np.tile(np.arange(0,40,10),(3,1))  # 3 times replicate means number of row , 1 replicate colums means how many times print same think
print(a)
print("*****************************")
a = a.T    #T means transverse
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*****************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [6]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [7]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [17]:
a = np.arange(0,4,10)
a.shape

(1,)

In [11]:
a = a[:,np.newaxis] #adds a new axis -->2d array
a.shape

(1, 1)

In [12]:
a

array([[0]])

In [18]:
#sorting of arrray
a = np.array([[5,4,3],[2,3,4]])
b = np.sort(a,axis=1)
a

array([[5, 4, 3],
       [2, 3, 4]])

In [19]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [2, 3, 4]])

In [20]:
import numpy as np

# Example array
a = np.array([1, 2.71828183, 7.3890561, 20.08553692, 54.59815003])

# Sum of all elements
print(np.sum(a))    # total sum

# 2D Array
x = np.array([[1, 2],
              [3, 4]])
print(x)

# Column-wise sum
print(x.sum(axis=0))   # [4, 6]

# Row-wise sum
print(x.sum(axis=1))   # [3, 7]

# Minimum and Maximum
print(x.min())   # 1
print(x.max())   # 4

# Index of minimum and maximum
print(x.argmin())  # 0  (position of 1 in flattened array)
print(x.argmax())  # 3  (position of 4 in flattened array)


85.79102488
[[1 2]
 [3 4]]
[4 6]
[3 7]
1
4
0
3
